// pages/birthstones/index.tsx
import Head from "next/head";
import Card from "react-bootstrap/Card";
import { birthstones } from "../../data";
import { getMonthFromIndex } from "../../helpers";

const BirthstonesPage = () => {
  return (
    <>
      <Head>
        <title>Birthstones | Aesthetics in Jewelry</title>
        <meta
          name="description"
          content="Aesthetics in Jewelry - Birthstones Page"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <article id="birthstones" className="container py-5">
        <h1 className="text-center pb-4">Birthstones</h1>
        <section>
          <div className="row">
            {birthstones.map((birthstone, index) => (
              <div className="col-12 col-md-4 col-lg-2 mb-3" key={index}>
                <Card className="text-center">
                  <Card.Img src={`/stone-${index + 1}.jpg`} alt={birthstone} />
                  <Card.Title className="pt-3">
                    {getMonthFromIndex(index)}
                  </Card.Title>
                  <Card.Subtitle className="text-muted pb-3">
                    ({birthstone})
                  </Card.Subtitle>
                  <Card.Footer>
                    <Card.Link
                      href={`/birthstones/${index + 1}`}
                      className="stretched-link"
                    >
                      Details
                    </Card.Link>
                  </Card.Footer>
                </Card>
              </div>
            ))}
          </div>
        </section>
      </article>
    </>
  );
};

export default BirthstonesPage;

// client/pages/birthstones.vue
<template>
  <section class="container">
    <h1 class="text-center pb-3">Birthstones</h1>
    <article>
      <div class="row">
        <div
          v-for="(b, index) in birthstones"
          :key="index"
          class="col-md-2 mb-3"
        >
          <a :href="`/birthstones/${index + 1}`" class="text-decoration-none">
            <div class="card shadow-lg">
              <img
                :src="require(`@/assets/stone-${index + 1}.jpg`)"
                :alt="`${b.month} ${b.stone}`"
                class="card-img-top"
              />
              <h6 class="card-title text-dark text-center">
                {{ b.month }} <span class="text-muted">({{ b.stone }})</span>
              </h6>
            </div>
          </a>
        </div>
      </div>
    </article>
  </section>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  data() {
    return {
      birthstones: [
        { month: "January", stone: "Garnet" },
        { month: "Februrary", stone: "Amethyst" },
        { month: "March", stone: "Aquamarine" },
        { month: "April", stone: "Diamond" },
        { month: "May", stone: "Emerald" },
        { month: "June", stone: "Pearl/Alexandrite" },
        { month: "July", stone: "Ruby" },
        { month: "August", stone: "Peridot" },
        { month: "September", stone: "Sapphire" },
        { month: "October", stone: "Opal/Tourmaline" },
        { month: "November", stone: "Citrine" },
        { month: "December", stone: "Blue Zirconia" }
      ]
    };
  }
});
</script>
