// src/components/ContactForm.tsx
import { useState } from "react";
import { useForm, SubmitHandler } from "react-hook-form";

type Inputs = {
  name: string;
  preferredMethod: string;
  methodInfo: string;
  message: string;
};

const ContactForm = () => {
  const [formSubmitted, setFormSubmitted] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<Inputs>();

  const onSubmit: SubmitHandler<Inputs> = async (data) => {
    try {
      setFormSubmitted(!formSubmitted);
      await fetch("/api/sendgrid", {
        method: "POST",
        body: JSON.stringify(data),
      });
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      {!formSubmitted ? (
        <form onSubmit={handleSubmit(onSubmit)}>
          <div className="mb-3">
            <label htmlFor="name" className="form-label">
              Name:
            </label>
            <input
              type="text"
              className="form-control"
              id="name"
              placeholder="Enter your name"
              required
              {...register("name")}
            />
          </div>

          <div className="mb-3">
            <label htmlFor="preferred-method-group">
              Preferred Method of Contact:
            </label>
            <br />
            <div
              id="preferred-method-group"
              className="btn-group"
              role="group"
              aria-label="Basic radio toggle button group"
            >
              <input
                type="radio"
                className="btn-check"
                name="preferred-method"
                id="phone"
                value="phone"
                {...register("preferredMethod")}
              />
              <label className="btn btn-outline-primary" htmlFor="phone">
                Phone
              </label>

              <input
                type="radio"
                className="btn-check"
                name="preferred-method"
                id="email"
                value="email"
                {...register("preferredMethod")}
              />
              <label className="btn btn-outline-primary" htmlFor="email">
                Email
              </label>
            </div>
          </div>

          <div className="mb-3">
            <label htmlFor="method-info" className="form-label">
              Please provide details, based on your preferences above:
            </label>
            <input
              type="text"
              className="form-control"
              id="method-info"
              placeholder="Contact details"
              required
              {...register("methodInfo")}
            />
          </div>

          <div className="mb-3">
            <label htmlFor="message" className="form-label">
              Message:
            </label>
            <textarea
              className="form-control"
              id="message"
              placeholder="Leave a comment"
              required
              {...register("message")}
            />
          </div>

          <button className="btn btn-primary" type="submit">
            Submit
          </button>
        </form>
      ) : (
        <p>Thanks! We&apos;ll get back to you as soon as we can.</p>
      )}
    </>
  );
};

export default ContactForm;

// components/ContactForm.vue
<template>
  <div>
    <form
      v-if="!sent"
      method="POST"
      data-netlify="true"
      data-netlify-honeypot="bot-field"
    >
      <input type="hidden" name="contact_us" value="contact_us" />
      <b-form-group label="Name:" label-for="input-name">
        <b-form-input id="input-name" name="name" required />
      </b-form-group>

      <label for="input-method">Preferred Contact Method:</label>
      <b-input-group class="pb-3">
        <b-input-group-prepend is-text>
          <b-form-radio-group
            name="method"
            :options="['Phone', 'Email']"
            required
          />
        </b-input-group-prepend>
        <b-form-input
          id="input-method"
          name="methodData"
          :placeholder="methodPlaceholder"
          required
        />
      </b-input-group>

      <b-form-group label="Message:" label-for="input-message">
        <b-form-textarea id="input-message" name="message" rows="3" required />
      </b-form-group>

      <button class="btn btn-primary" type="submit">Submit</button>
    </form>

    <p v-else>
      Thanks for your submission! We'll get back to you as soon as possible.
    </p>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  data() {
    return {
      form: {
        name: null,
        method: null,
        methodData: null,
        message: null,
      },
      sent: false,
    };
  },
  computed: {
    methodPlaceholder() {
      switch (this.form.method as string | null) {
        case "Phone":
          return "Please enter a phone number";
        case "Email":
          return "Please enter an email address";
        default:
          return "Please select a method";
      }
    },
  },
  // methods: {
  //   submitContactForm(e: Event) {
  //     this.sent = true;
  //     const { name, method, methodData, message } = Object.fromEntries(
  //       new FormData(e.target)
  //     );
  //   },
  // },
});
</script>
