// components/ContactForm.vue
<template>
  <div>
    <form
      v-if="!sent"
      method="POST"
      data-netlify="true"
      data-netlify-honeypot="bot-field"
    >
      <input type="hidden" name="contact_us" value="contact_us" />
      <b-form-group label="Name:" label-for="input-name">
        <b-form-input id="input-name" name="name" required />
      </b-form-group>

      <label for="input-method">Preferred Contact Method:</label>
      <b-input-group class="pb-3">
        <b-input-group-prepend is-text>
          <b-form-radio-group
            name="method"
            :options="['Phone', 'Email']"
            required
          />
        </b-input-group-prepend>
        <b-form-input
          id="input-method"
          name="methodData"
          :placeholder="methodPlaceholder"
          required
        />
      </b-input-group>

      <b-form-group label="Message:" label-for="input-message">
        <b-form-textarea id="input-message" name="message" rows="3" required />
      </b-form-group>

      <button class="btn btn-primary" type="submit">Submit</button>
    </form>

    <p v-else>
      Thanks for your submission! We'll get back to you as soon as possible.
    </p>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  data() {
    return {
      form: {
        name: null,
        method: null,
        methodData: null,
        message: null,
      },
      sent: false,
    };
  },
  computed: {
    methodPlaceholder() {
      switch (this.form.method as string | null) {
        case "Phone":
          return "Please enter a phone number";
        case "Email":
          return "Please enter an email address";
        default:
          return "Please select a method";
      }
    },
  },
  // methods: {
  //   submitContactForm(e: Event) {
  //     this.sent = true;
  //     const { name, method, methodData, message } = Object.fromEntries(
  //       new FormData(e.target)
  //     );
  //   },
  // },
});
</script>

// components/ContactForm.tsx
import { useState } from "react";
import Button from "react-bootstrap/Button";
import Form from "react-bootstrap/Form";
import { useForm, SubmitHandler } from "react-hook-form";

type Inputs = {
  name: string;
  preferredMethod: string;
  methodInfo: string;
  message: string;
};

const ContactForm = () => {
  const [formSubmitted, setFormSubmitted] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<Inputs>();

  const onSubmit: SubmitHandler<Inputs> = () =>
    setFormSubmitted(!formSubmitted);

  return (
    <>
      {!formSubmitted ? (
        <Form onSubmit={handleSubmit(onSubmit)}>
          <Form.Group className="mb-3" controlId="formDataName">
            <Form.Label>Name:</Form.Label>
            <Form.Control
              type="text"
              placeholder="Enter your name"
              required
              {...register("name")}
            />
          </Form.Group>

          <Form.Group className="mb-3">
            <Form.Label>Preferred Method of Contact:</Form.Label>
            <Form.Check
              inline
              type="radio"
              label="Phone"
              value="phone"
              {...register("preferredMethod")}
              className="ml-3"
            />
            <Form.Check
              inline
              type="radio"
              label="Email"
              value="email"
              {...register("preferredMethod")}
            />
          </Form.Group>

          <Form.Group className="mb-3" controlId="formDataMethodInfo">
            <Form.Label>
              Please provide details, based on your preferences above:
            </Form.Label>
            <Form.Control
              type="text"
              placeholder="Please provide details, based on your preferences above"
              required
              {...register("methodInfo")}
            />
          </Form.Group>

          <Form.Group className="mb-3" controlId="formDataMessage">
            <Form.Label>Message:</Form.Label>
            <Form.Control
              as="textarea"
              placeholder="Leave a comment here"
              required
              {...register("message")}
            />
          </Form.Group>

          <Button variant="primary" type="submit">
            Submit
          </Button>
        </Form>
      ) : (
        <p>Thanks! We'll get back to you as soon as we can.</p>
      )}
    </>
  );
};

export default ContactForm;
