// src/components/Header.tsx
import Link from "next/link";

const Header = () => {
  return (
    <header>
      <nav className="navbar navbar-expand-lg navbar-light bg-transparent">
        <div className="container py-3">
          <Link href="/">
            <a className="navbar-brand">Aesthetics in Jewelry</a>
          </Link>
          <button
            className="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarSupportedContent">
            <span className="navbar-text">
              Let&apos;s find you some amazing jewelry!
            </span>
            <ul className="navbar-nav ms-auto">
              <li className="nav-item">
                <Link href="/">
                  <a className="nav-link" aria-current="page">
                    Home
                  </a>
                </Link>
              </li>
              <li className="nav-item">
                <Link href="/about">
                  <a className="nav-link" aria-current="page">
                    About Us
                  </a>
                </Link>
              </li>
              <li className="nav-item">
                <Link href="/exceptionals">
                  <a className="nav-link" aria-current="page">
                    Exceptionals
                  </a>
                </Link>
              </li>
              <li className="nav-item">
                <Link href="/birthstones">
                  <a className="nav-link" aria-current="page">
                    Birthstones
                  </a>
                </Link>
              </li>
              <li className="nav-item">
                <Link href="/services">
                  <a className="nav-link" aria-current="page">
                    Services
                  </a>
                </Link>
              </li>
              <li className="nav-item">
                <Link href="/visit">
                  <a className="nav-link" aria-current="page">
                    Visit Us
                  </a>
                </Link>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  );
};

export default Header;

// components/Header.vue
<template>
  <header class="container">
    <div class="d-none d-md-block">
      <b-navbar toggleable="md" type="light" variant="transparent">
        <span class="navbar-text">Let's find you some amazing jewelry!</span>
        <b-collapse is-nav>
          <b-navbar-nav class="ml-auto">
            <b-nav-item href="mailto:info@aestheticsinjewelry.com">
              Email
            </b-nav-item>
            <b-nav-item href="tel:5025892728">Phone</b-nav-item>
            <b-nav-item href="/visit-us">Youtube</b-nav-item>
            <b-nav-item href="">Facebook</b-nav-item>
            <b-nav-item href="/services">Instagram</b-nav-item>
            <b-nav-item href="">Our Business Page</b-nav-item>
          </b-navbar-nav>
        </b-collapse>
      </b-navbar>
      <hr class="my-0" />
    </div>
    <b-navbar toggleable="md" type="light" variant="transparent">
      <b-navbar-brand href="/">
        <b-img :src="require('@/assets/aj-logo.png')" width="200" />
      </b-navbar-brand>
      <b-navbar-toggle target="nav-collapse"></b-navbar-toggle>
      <b-collapse id="nav-collapse" is-nav>
        <b-navbar-nav class="ml-auto">
          <b-nav-item href="/about">About Us</b-nav-item>
          <b-nav-item href="/exceptionals">Exceptionals</b-nav-item>
          <b-nav-item href="/birthstones">Birthstones</b-nav-item>
          <b-nav-item href="/services">Services</b-nav-item>
          <b-nav-item href="/visit-us">Visit Us!</b-nav-item>
        </b-navbar-nav>
      </b-collapse>
    </b-navbar>
  </header>
</template>
