// client/pages/about.vue
<template>
  <section class="container">
    <h1 class="text-center pb-3">About Us</h1>
    <article>
      <p>
        Aesthetics in Jewelry was founded in 1976 by James Jackson (Jimmy the
        Jeweler). He was born in New Albany, Indiana, grew up in Louisville,
        Kentucky, and has lived in New London, Connecticut, and Kennewick,
        Washington, but now resides in Louisville, Kentucky.
      </p>

      <p>
        Following a six year service in the United States Navy Nuclear Power
        Program, Jim moved to Kennewick, Washington as a nuclear reactor
        operator. This is where his love for creating jewelry began as a hobby.
        Jim studied under Wes Door, a semi-retired mad scientist-type jeweler
        whom also invented a number of tools that are used standardly throughout
        the jewelry industry.
      </p>

      <p>
        While cutting gems and creating jewelry, Jim's passion grew to the point
        of a career change. Upon choosing jewelry as his life's work, he moved
        back to his hometown of Louisville, Kentucky. His shop was set up in his
        mother's basement, where he did repairs and made custom jewelry for
        local stores and personal customers.
      </p>

      <p>
        Aesthetics first moved to the Commonwealth building and was joined by
        several highly skilled benchmen. They later moved to their current
        location in the Chestnut Center between 4th and 5th Street, on the sixth
        floor and occupies almost the full length of one side of the building.
      </p>

      <p>
        The Chestnut Center has its own history, as it was originally the
        Francis Building, then Lincoln Square, and now the Chestnut Center.
        Aesthetics has changed addresses multiple times without changing its
        location. Aesthetics also has the convenience of free parking.
      </p>

      <p>
        Aesthetics is very fortunate to have a fully-equipped modern shop,
        manned by exceptional bench jewelers who make and repair jewelry with a
        high degree of perfection, and a very knowledgeable family-like staff.
        It's as if you're in a living room with friendly people helping you look
        through a treasure chest.
      </p>

      <p>
        Aesthetics is rooted in service and repairs; However, their strength is
        in the unique, the unusual, custom work and great values they provide.
        They maintain a full line of Ruby, Emerald, Sapphire, and Diamond
        jewelry and loose stones. They also have many rare and unusual items and
        stones that are not mainstream.
      </p>
    </article>
  </section>
</template>

// pages/about.tsx
import Head from "next/head";

const AboutPage = () => {
  return (
    <>
      <Head>
        <title>About Us | Aesthetics in Jewelry</title>
        <meta
          name="description"
          content="Aesthetics in Jewelry - About Us Page"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <article id="about" className="container py-5">
        <h1 className="text-center pb-4">About Us</h1>
        <p>
          Aesthetics in Jewelry was founded in 1976 by James Jackson (Jimmy the
          Jeweler). He was born in New Albany, Indiana, grew up in Louisville,
          Kentucky, and has lived in New London, Connecticut, and Kennewick,
          Washington, but now resides in Louisville, Kentucky.
        </p>

        <p>
          Following a six year service in the United States Navy Nuclear Power
          Program, Jim moved to Kennewick, Washington as a nuclear reactor
          operator. This is where his love for creating jewelry began as a
          hobby. Jim studied under Wes Door, a semi-retired mad scientist-type
          jeweler whom also invented a number of tools that are used standardly
          throughout the jewelry industry.
        </p>

        <p>
          While cutting gems and creating jewelry, Jim's passion grew to the
          point of a career change. Upon choosing jewelry as his life's work, he
          moved back to his hometown of Louisville, Kentucky. His shop was set
          up in his mother's basement, where he did repairs and made custom
          jewelry for local stores and personal customers.
        </p>

        <p>
          Aesthetics first moved to the Commonwealth building and was joined by
          several highly skilled benchmen. They later moved to their current
          location in the Chestnut Center between 4th and 5th Street, on the
          sixth floor and occupies almost the full length of one side of the
          building.
        </p>

        <p>
          The Chestnut Center has its own history, as it was originally the
          Francis Building, then Lincoln Square, and now the Chestnut Center.
          Aesthetics has changed addresses multiple times without changing its
          location. Aesthetics also has the convenience of free parking.
        </p>

        <p>
          Aesthetics is very fortunate to have a fully-equipped modern shop,
          manned by exceptional bench jewelers who make and repair jewelry with
          a high degree of perfection, and a very knowledgeable family-like
          staff. It's as if you're in a living room with friendly people helping
          you look through a treasure chest.
        </p>

        <p>
          Aesthetics is rooted in service and repairs; However, their strength
          is in the unique, the unusual, custom work and great values they
          provide. They maintain a full line of Ruby, Emerald, Sapphire, and
          Diamond jewelry and loose stones. They also have many rare and unusual
          items and stones that are not mainstream.
        </p>
      </article>
    </>
  );
};

export default AboutPage;
